import 'dart:developer';
import 'dart:io';

void main(List<String> arguments) {
  // final argParser = ArgParser()
  //   ..addOption('name', abbr: 'n', defaultsTo: 'NamedRoutes');

  // final results = argParser.parse(arguments);
  // final enumName = results['name'] as String;
  const enumName ='NamedRoutes';
  const fileName = 'named_routes';


  final enumValues = ["initial"];

  final fileContent = ''' 
// Hint :  This file is generated by go_init.dart update it manually but don't delete it 

enum $enumName {
  ${enumValues.map((e) => '$e(\'/\');').join('\n  ')}
  
  ///TODO: add your routes here and give each route a name starting with /   
  
  final String routeName;
  const $enumName(this.routeName);
}
''';
/// file as lower case => named_routes.dart
  final file = File("lib/$fileName.dart");
  file.writeAsStringSync(fileContent);

  log("$enumName enum file has been generated successfully in lib/src/generated/");
}
