name: easy_go
description: A Flutter package for easy routing and navigation
version: 1.0.0
homepage: https://github.com/Asherbinyy/Easy-Go.git
#authors:
#  - Sherbini <ahmed.elsherbiny2020@gmail.com>


environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

