// Hint :  This file is generated by go_init.dart update it manually but don't delete it 

enum NamedRoutes {
  initial('/');
  
  ///TODO: add your routes here and give each route a name starting with /   
  
  final String routeName;
  const NamedRoutes(this.routeName);
}
